// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FinishUninstall() {
  return window['go']['main']['App']['FinishUninstall']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAutoStart() {
  return window['go']['main']['App']['GetAutoStart']();
}

export function GetBootReport() {
  return window['go']['main']['App']['GetBootReport']();
}

export function GetConnectTrace() {
  return window['go']['main']['App']['GetConnectTrace']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetPendingUpdate() {
  return window['go']['main']['App']['GetPendingUpdate']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetTuningReport() {
  return window['go']['main']['App']['GetTuningReport']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function RunServiceCheck() {
  return window['go']['main']['App']['RunServiceCheck']();
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function StartBypass() {
  return window['go']['main']['App']['StartBypass']();
}

export function StopBypass() {
  return window['go']['main']['App']['StopBypass']();
}

export function Uninstall() {
  return window['go']['main']['App']['Uninstall']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
