// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {engine} from '../models';
import {settings} from '../models';

export function GetAppVersion():Promise<string>;

export function GetAutoStart():Promise<boolean>;

export function GetBootReport():Promise<main.BootReport>;

export function GetConnectTrace():Promise<Array<engine.ProgressEvent>>;

export function GetLogs():Promise<string>;

export function GetPendingUpdate():Promise<string>;

export function GetSettings():Promise<settings.Config>;

export function GetState():Promise<engine.Status>;

export function GetTuningReport():Promise<engine.TuningReport>;

export function InstallUpdate():Promise<string>;

export function RunServiceCheck():Promise<Array<engine.ServiceCheck>>;

export function SetAutoStart(arg1:boolean):Promise<string>;

export function StartBypass():Promise<string>;

export function StopBypass():Promise<string>;

export function UpdateSettings(arg1:settings.Config):Promise<string>;
